-- Supabase seed: Intentionally empty
--
-- Auth triggers (handle_new_user, custom_access_token_hook) are installed
-- AFTER Prisma migrations via supabase/auth-triggers.sql.
--
-- Reason: seed.sql runs during `supabase start` BEFORE Prisma tables exist,
-- so referencing public."User" / public."Provider" here causes:
--   ERROR: relation "public.User" does not exist
--
-- See: supabase/auth-triggers.sql for the actual trigger definitions.
