/**
 * Pre-generates article data from markdown files.
 * Produces src/lib/help/articles-data.ts (static import, no fs needed at runtime).
 *
 * Run: npx tsx scripts/generate-help-data.ts
 * Chained automatically via `prebuild` in package.json.
 */

import fs from "fs"
import path from "path"

// Inline the parse logic (same as loader.ts parseArticleMarkdown + parseFrontmatter + parseBody)
// We duplicate here to avoid importing from src/ which may have path alias issues in scripts.

interface HelpContent {
  heading?: string
  paragraphs?: string[]
  steps?: string[]
  bullets?: string[]
  tip?: string
}

interface HelpArticle {
  slug: string
  title: string
  role: string
  section: string
  keywords: string[]
  summary: string
  content: HelpContent[]
}

function parseFrontmatter(raw: string): Record<string, string | string[]> {
  const result: Record<string, string | string[]> = {}
  const lines = raw.split("\n")
  let currentKey = ""

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue

    if (trimmed.startsWith("- ") && currentKey) {
      const existing = result[currentKey]
      const value = trimmed.slice(2).trim()
      if (Array.isArray(existing)) {
        existing.push(value)
      } else {
        result[currentKey] = [value]
      }
      continue
    }

    const colonIdx = trimmed.indexOf(":")
    if (colonIdx === -1) continue

    const key = trimmed.slice(0, colonIdx).trim()
    let value = trimmed.slice(colonIdx + 1).trim()
    currentKey = key

    if (value.startsWith("[") && value.endsWith("]")) {
      result[key] = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean)
      continue
    }

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    if (value) {
      result[key] = value
    }
  }

  return result
}

function hasContent(block: HelpContent): boolean {
  return !!(
    block.heading ||
    block.paragraphs?.length ||
    block.steps?.length ||
    block.bullets?.length ||
    block.tip
  )
}

function parseBody(body: string): HelpContent[] {
  const blocks: HelpContent[] = []
  let current: HelpContent = {}

  function flushBlock() {
    if (hasContent(current)) {
      blocks.push(current)
    }
    current = {}
  }

  const lines = body.split("\n")
  for (const line of lines) {
    const trimmed = line.trim()

    if (trimmed === "---") { flushBlock(); continue }
    if (trimmed.startsWith("## ")) { flushBlock(); current.heading = trimmed.slice(3).trim(); continue }
    if (trimmed.startsWith("> **Tips:**")) { current.tip = trimmed.slice("> **Tips:**".length).trim(); continue }

    const stepMatch = trimmed.match(/^\d+\.\s+(.+)$/)
    if (stepMatch) { if (!current.steps) current.steps = []; current.steps.push(stepMatch[1]); continue }
    if (trimmed.startsWith("- ")) { if (!current.bullets) current.bullets = []; current.bullets.push(trimmed.slice(2)); continue }
    if (!trimmed) continue

    if (!current.paragraphs) current.paragraphs = []
    current.paragraphs.push(trimmed)
  }

  flushBlock()
  return blocks
}

function parseArticleMarkdown(markdown: string): HelpArticle {
  const fmMatch = markdown.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!fmMatch) throw new Error("Invalid markdown: missing frontmatter")

  const fm = parseFrontmatter(fmMatch[1])
  const body = fmMatch[2]

  return {
    slug: fm.slug as string,
    title: fm.title as string,
    role: fm.role as string,
    section: fm.section as string,
    keywords: Array.isArray(fm.keywords) ? fm.keywords : (fm.keywords ? [fm.keywords as string] : []),
    summary: fm.summary as string,
    content: parseBody(body),
  }
}

// Read all markdown files
const articlesDir = path.join(process.cwd(), "src", "lib", "help", "articles")
const allArticles: HelpArticle[] = []

for (const role of ["customer", "provider", "admin"]) {
  const dir = path.join(articlesDir, role)
  if (!fs.existsSync(dir)) continue
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md"))
  for (const file of files) {
    const content = fs.readFileSync(path.join(dir, file), "utf-8")
    allArticles.push(parseArticleMarkdown(content))
  }
}

// Generate TypeScript file
const output = `// AUTO-GENERATED by scripts/generate-help-data.ts
// Do not edit manually. Edit markdown files in src/lib/help/articles/ instead.
// Regenerate with: npx tsx scripts/generate-help-data.ts

import type { HelpArticle } from "./types"

export const allArticles: HelpArticle[] = ${JSON.stringify(allArticles, null, 2)} as const satisfies HelpArticle[]
`

const outPath = path.join(process.cwd(), "src", "lib", "help", "articles-data.ts")
fs.writeFileSync(outPath, output, "utf-8")
console.log(`Generated ${outPath} with ${allArticles.length} articles`)
