// AUTO-GENERATED by scripts/generate-help-data.ts
// Do not edit manually. Edit markdown files in src/lib/help/articles/ instead.
// Regenerate with: npx tsx scripts/generate-help-data.ts

import type { HelpArticle } from "./types"

export const allArticles: HelpArticle[] = [
  {
    "slug": "aterkommande-bokning",
    "title": "Återkommande bokning",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "återkommande",
      "regelbunden",
      "serie",
      "intervall",
      "schema",
      "automatisk",
      "vecka",
      "hovbeläggning"
    ],
    "summary": "Skapa en återkommande bokning som schemalägger flera tillfällen automatiskt med valfritt intervall.",
    "content": [
      {
        "paragraphs": [
          "Om du behöver regelbundna besök (t.ex. hovbeläggning var 8:e vecka) kan du skapa en återkommande bokning som schemalägger flera tillfällen automatiskt.",
          "Förutsättning: Leverantören måste ha aktiverat återkommande bokningar i sina inställningar."
        ]
      },
      {
        "heading": "Skapa en återkommande bokning",
        "steps": [
          "Börja boka som vanligt (välj leverantör, tjänst, datum och tid)",
          "Slå på \"Gör detta återkommande\"",
          "Välj intervall: varje vecka, varannan vecka, var 4:e, 6:e eller 8:e vecka",
          "Välj antal tillfällen: 2, 4, 6, 8 eller 12",
          "Bekräfta bokningen"
        ]
      },
      {
        "paragraphs": [
          "Systemet skapar alla bokningar i serien automatiskt. Datum som krockar med leverantörens schema (stängt, redan fullbokat, för kort restid) hoppas över -- du ser vilka datum som hoppades över och varför i resultatdialogen."
        ]
      },
      {
        "heading": "Resultatdialog",
        "bullets": [
          "Hur många bokningar som skapades (t.ex. \"8 av 8 bokningar skapades\")",
          "Startdatum och intervall",
          "Om några datum hoppades över visas de med anledning"
        ]
      },
      {
        "heading": "I bokningslistan",
        "paragraphs": [
          "Bokningar som tillhör en serie markeras med en lila \"Återkommande\"-badge i din bokningslista. Varje bokning i serien kan avbokas individuellt utan att påverka övriga bokningar i serien."
        ]
      },
      {
        "heading": "E-postbekräftelse",
        "paragraphs": [
          "Du får en bekräftelse via e-post med en lista över alla skapade datum i serien."
        ]
      },
      {
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "betalning-och-kvitto",
    "title": "Betalning och kvitto",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "betala",
      "betalning",
      "kvitto",
      "PDF",
      "faktura",
      "pris",
      "kr",
      "fakturanummer"
    ],
    "summary": "Betala för bekräftade bokningar direkt i appen och ladda ner kvitto som PDF.",
    "content": [
      {
        "paragraphs": [
          "När en bokning är bekräftad eller genomförd kan du betala direkt i appen."
        ]
      },
      {
        "heading": "Så här betalar du",
        "steps": [
          "Gå till Mina bokningar",
          "Klicka Betala X kr på den aktuella bokningen",
          "Betalningen behandlas och du får ett kvittonummer",
          "Kvittot kan laddas ner som PDF"
        ]
      },
      {
        "paragraphs": [
          "Kvittot innehåller fakturanummer (format: EQ-YYYYMM-XXXX), datum, tjänst, belopp och leverantörsinformation."
        ]
      }
    ]
  },
  {
    "slug": "boka-en-tjanst",
    "title": "Boka en tjänst",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "boka",
      "bokning",
      "tid",
      "datum",
      "kalender",
      "bekräfta",
      "häst",
      "tjänst",
      "traditionell"
    ],
    "summary": "Boka en tjänst genom att välja leverantör, tjänst, datum, tid och häst.",
    "content": [
      {
        "paragraphs": [
          "Traditionell bokning innebär att du väljer ett specifikt datum och en tid."
        ]
      },
      {
        "heading": "Så här bokar du",
        "steps": [
          "Gå till leverantörens profil",
          "Välj den tjänst du vill boka",
          "Välj datum i kalendern (lediga dagar visas)",
          "Välj en ledig tid",
          "Välj häst från ditt register (eller skriv hästens namn manuellt)",
          "Lägg till eventuella kommentarer eller önskemål",
          "Granska en sammanfattning av bokningen (tjänst, datum, tid, häst)",
          "Bekräfta bokningen"
        ]
      },
      {
        "heading": "Vad händer sen?",
        "bullets": [
          "Leverantören får en notifikation om din bokning",
          "Du får besked när leverantören accepterar eller avböjer",
          "Vid bekräftelse kan du betala direkt i appen"
        ]
      },
      {
        "paragraphs": [
          "Systemet kontrollerar automatiskt att det inte finns dubbelbokningar och att det finns tillräckligt med restid mellan leverantörens bokningar."
        ]
      }
    ]
  },
  {
    "slug": "bokningspaminnelser",
    "title": "Bokningspåminnelser",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "påminnelse",
      "24 timmar",
      "e-post",
      "checklista",
      "förberedelse",
      "avprenumerera"
    ],
    "summary": "Få automatiska påminnelser 24 timmar innan varje bekräftad bokning med förberedelsechecklista.",
    "content": [
      {
        "paragraphs": [
          "Du får automatiskt en påminnelse 24 timmar innan varje bekräftad bokning."
        ]
      },
      {
        "heading": "Påminnelsen innehåller",
        "bullets": [
          "Datum, tid och tjänst",
          "Leverantörens namn",
          "Förberedelsechecklista (lugn miljö, upplyst, plant underlag, ren häst)"
        ]
      },
      {
        "heading": "Hur påminnelserna skickas",
        "bullets": [
          "E-post med bokningsdetaljer och checklista",
          "In-app-notifikation i klockikonen"
        ]
      },
      {
        "heading": "Stänga av påminnelser",
        "bullets": [
          "Klicka på unsubscribe-länken i påminnelsemailet",
          "Eller gå till Min profil och inaktivera e-postpåminnelser"
        ]
      },
      {
        "paragraphs": [
          "Du kan när som helst slå på påminnelser igen via din profil."
        ]
      }
    ]
  },
  {
    "slug": "dataexport",
    "title": "Dataexport",
    "role": "customer",
    "section": "Konto",
    "keywords": [
      "export",
      "data",
      "GDPR",
      "JSON",
      "CSV",
      "personuppgifter",
      "ladda ner"
    ],
    "summary": "Exportera all din personliga data i JSON- eller CSV-format enligt GDPR.",
    "content": [
      {
        "paragraphs": [
          "Du har rätt att exportera all din personliga data (GDPR)."
        ]
      },
      {
        "heading": "Så här exporterar du din data",
        "steps": [
          "Gå till Min profil",
          "Klicka Exportera min data",
          "Välj format: JSON eller CSV",
          "Filen laddas ner direkt"
        ]
      },
      {
        "heading": "Exporten innehåller",
        "bullets": [
          "Personuppgifter (namn, e-post)",
          "Alla bokningar med status och detaljer",
          "Hästregister med anteckningar",
          "Recensioner du skrivit"
        ]
      }
    ]
  },
  {
    "slug": "flexibel-bokning",
    "title": "Flexibel bokning",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "flexibel",
      "beställning",
      "rutt",
      "datumintervall",
      "akut",
      "prioritet",
      "adress",
      "order"
    ],
    "summary": "Skapa en flexibel beställning utan exakt tid så att leverantören lägger in dig i en rutt när det passar.",
    "content": [
      {
        "paragraphs": [
          "Om du inte behöver en exakt tid kan du skapa en flexibel beställning. Leverantören lägger då in dig i en rutt när det passar."
        ]
      },
      {
        "heading": "Skapa en flexibel beställning",
        "steps": [
          "Gå till Beställningar eller bläddra bland leverantörers annonserade rutter",
          "Välj tjänstetyp (t.ex. \"Hovbeläggning\")",
          "Ange din adress",
          "Välj ett datumintervall (t.ex. \"15 feb - 1 mar\")",
          "Ange antal hästar",
          "Välj prioritet: Normal eller Akut",
          "Lägg till eventuella instruktioner (t.ex. \"Parkera vid röda ladan\")"
        ]
      },
      {
        "paragraphs": [
          "Om en leverantör redan har annonserat en rutt i ditt område kan du ansluta dig direkt till den rutten.",
          "Du får en notifikation när leverantören har planerat in dig i en rutt, inklusive beräknad ankomsttid."
        ]
      }
    ]
  },
  {
    "slug": "folj-leverantor",
    "title": "Följ leverantör",
    "role": "customer",
    "section": "Sökning",
    "keywords": [
      "följ",
      "leverantör",
      "ruttannons",
      "kommun",
      "personlig",
      "notifikation",
      "servicebehov"
    ],
    "summary": "Följ leverantörer du gillar för att få personliga ruttannonser och servicemeddelanden.",
    "content": [
      {
        "paragraphs": [
          "Du kan följa leverantörer du gillar för att få personliga ruttannonser."
        ]
      },
      {
        "heading": "Följ en leverantör",
        "steps": [
          "Gå till leverantörens profil",
          "Klicka Följ",
          "Knappen ändras till Följer (klicka igen för att sluta följa)"
        ]
      },
      {
        "heading": "Välj kommun",
        "paragraphs": [
          "För att få relevanta ruttannonser behöver du ange vilken kommun du befinner dig i."
        ],
        "steps": [
          "Gå till Min profil",
          "Välj kommun i dropdown-menyn",
          "Spara"
        ]
      },
      {
        "heading": "Personliga ruttannonser",
        "paragraphs": [
          "När en leverantör du följer annonserar en rutt i din kommun får du en notifikation. Om din häst dessutom är försenad för service får du ett personligt meddelande med information om både hästens servicebehov och leverantörens lediga tider.",
          "Exempel: \"Blansen behövde skoning för 2 veckor sedan. Anna har lediga tider i Kungsbacka nästa vecka.\""
        ]
      },
      {
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "gruppbokning",
    "title": "Gruppbokning",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "grupp",
      "gruppbokning",
      "stall",
      "inbjudningskod",
      "kod",
      "dela",
      "tillsammans",
      "grupprequest"
    ],
    "summary": "Skapa eller gå med i en gruppbokning med andra hästägare på samma stall eller i samma område.",
    "content": [
      {
        "paragraphs": [
          "Om ni är flera hästägare på samma stall eller i samma område kan ni skapa en grupprequest och boka tillsammans. Det ger leverantören möjlighet att planera in alla i samma besök."
        ]
      },
      {
        "heading": "Skapa en grupprequest",
        "steps": [
          "Gå till Gruppbokning i menyn",
          "Välj tjänstetyp (t.ex. \"Hovbeläggning\")",
          "Ange plats och ett datumintervall",
          "Systemet skapar en unik inbjudningskod (8 tecken)",
          "Dela koden med andra hästägare"
        ]
      },
      {
        "heading": "Gå med i en grupp",
        "bullets": [
          "Ange inbjudningskoden eller klicka på en delad länk",
          "Fyll i information om din häst",
          "Du ser hur många som redan gått med"
        ]
      },
      {
        "heading": "Vad händer sen?",
        "bullets": [
          "Leverantörer ser öppna grupprequests i sitt område",
          "När en leverantör matchar gruppen skapas individuella bokningar för alla deltagare",
          "Du får en notifikation med datum, tid och leverantörsinformation"
        ]
      },
      {
        "paragraphs": [
          "Du kan lämna en grupp innan den matchats. Om du är den som skapade gruppen kan du även avbryta hela requesten."
        ]
      }
    ]
  },
  {
    "slug": "halsotidslinje",
    "title": "Hälsotidslinje",
    "role": "customer",
    "section": "Hästar",
    "keywords": [
      "hälsa",
      "tidslinje",
      "historik",
      "anteckning",
      "veterinär",
      "hovvård",
      "medicinering",
      "skada",
      "vårdhistorik"
    ],
    "summary": "Se hela hästens vårdhistorik kronologiskt med bokningar och egna hälsoanteckningar.",
    "content": [
      {
        "paragraphs": [
          "Varje registrerad häst har en hälsotidslinje som samlar all vårdinformation kronologiskt."
        ]
      },
      {
        "heading": "Tidslinjen visar",
        "bullets": [
          "Genomförda bokningar (hovslagare, veterinär, etc.)",
          "Hälsoanteckningar du lagt till själv"
        ]
      },
      {
        "heading": "Kategorier för anteckningar",
        "bullets": [
          "Veterinär (vaccinationer, hälsokontroller)",
          "Hovvård (skoning, verkning)",
          "Skada (skador, olyckor)",
          "Medicinering (läkemedel, doser)",
          "Övrigt (egna observationer)"
        ]
      },
      {
        "paragraphs": [
          "Du kan filtrera tidslinjen per kategori och lägga till nya anteckningar när som helst. Det här ger dig och dina leverantörer en komplett bild av hästens vårdhistorik."
        ]
      }
    ]
  },
  {
    "slug": "hantera-bokningar",
    "title": "Hantera bokningar",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "bokningar",
      "status",
      "avboka",
      "betala",
      "omdöme",
      "bekräftad",
      "genomförd",
      "väntar",
      "filtrera"
    ],
    "summary": "Se och hantera alla dina bokningar med statusöversikt, filtrering och möjlighet att avboka eller betala.",
    "content": [
      {
        "paragraphs": [
          "Under Mina bokningar ser du alla dina bokningar med status."
        ]
      },
      {
        "heading": "Statusar",
        "bullets": [
          "Väntar på svar -- Leverantören har inte svarat ännu",
          "Bekräftad -- Leverantören har accepterat",
          "Genomförd -- Tjänsten är utförd",
          "Ej infunnit -- Du dök inte upp till bokningen",
          "Avbokad -- Bokningen är avbokad"
        ]
      },
      {
        "heading": "Du kan",
        "bullets": [
          "Filtrera på kommande, tidigare eller alla bokningar",
          "Avboka en bokning (om den inte redan är betald)",
          "Boka om en bokning (om leverantören tillåter det)",
          "Betala för bekräftade bokningar",
          "Lämna omdöme efter genomförd bokning"
        ]
      },
      {
        "heading": "Boka om en bokning",
        "paragraphs": [
          "Om leverantören har aktiverat självservice-ombokning kan du byta tid på en bekräftad bokning utan att behöva kontakta leverantören.",
          "Ombokning är inte tillgänglig om:"
        ],
        "steps": [
          "Gå till Mina bokningar",
          "Klicka på den bokning du vill boka om",
          "Klicka **Boka om**",
          "Välj ett nytt datum och tid",
          "Bekräfta -- den gamla bokningstiden ersätts"
        ],
        "bullets": [
          "Leverantören inte har aktiverat funktionen",
          "Bokningstiden är för nära inpå (leverantören sätter gränsen)",
          "Bokningen redan är betald"
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "hastprofil",
    "title": "Hästprofil",
    "role": "customer",
    "section": "Hästar",
    "keywords": [
      "profil",
      "dela",
      "länk",
      "veterinär",
      "försäkring",
      "vårdhistorik",
      "utskrift",
      "delbar"
    ],
    "summary": "Skapa en delbar länk till din hästs uppgifter och vårdhistorik som är giltig i 30 dagar.",
    "content": [
      {
        "paragraphs": [
          "Du kan skapa en delbar länk till din hästs uppgifter och vårdhistorik -- en digital hästprofil."
        ]
      },
      {
        "heading": "Skapa en delbar hästprofil",
        "steps": [
          "Gå till din häst under Mina hästar",
          "Klicka Dela hästprofil",
          "En unik länk skapas som är giltig i 30 dagar",
          "Dela länken med veterinär, ny ägare eller försäkringsbolag"
        ]
      },
      {
        "heading": "Vad visas i hästprofilen",
        "bullets": [
          "Hästens grunduppgifter (namn, ras, födelseår, kön, foto)",
          "UELN-nummer och mikrochip-ID (om registrerat)",
          "Vårdhistorik: veterinär, hovvård, skador och medicinering",
          "Utskriftsvänlig layout"
        ]
      },
      {
        "heading": "Integritetsskydd",
        "paragraphs": [
          "Privata anteckningar (kategorin \"Övrigt\") visas inte i hästprofilen. Länken kräver ingen inloggning men upphör automatiskt efter 30 dagar."
        ]
      }
    ]
  },
  {
    "slug": "hastregistret",
    "title": "Hästregistret",
    "role": "customer",
    "section": "Hästar",
    "keywords": [
      "häst",
      "registrera",
      "namn",
      "ras",
      "UELN",
      "mikrochip",
      "foto",
      "kön",
      "färg",
      "födelseår"
    ],
    "summary": "Registrera och hantera dina hästar med uppgifter som ras, UELN-nummer, foto och medicinsk information.",
    "content": [
      {
        "paragraphs": [
          "Under Mina hästar kan du registrera och hantera alla dina hästar."
        ]
      },
      {
        "heading": "Lägg till häst",
        "bullets": [
          "Namn (obligatoriskt)",
          "Ras",
          "Födelseår",
          "Färg",
          "Kön (sto, valack, hingst)",
          "UELN-nummer (Unique Equine Life Number, max 15 tecken)",
          "Mikrochip-ID (max 15 tecken)",
          "Särskilda behov och medicinsk information",
          "Foto (dra och släpp eller klicka för att ladda upp)"
        ]
      },
      {
        "heading": "Fördelar med att registrera hästar",
        "bullets": [
          "Vid bokning kan du välja häst från en dropdown istället för att skriva manuellt",
          "All bokningshistorik kopplas till rätt häst",
          "Hälsotidslinjen ger en samlad bild av vård och behandlingar",
          "Foto gör det lättare att identifiera hästen"
        ]
      },
      {
        "paragraphs": [
          "Borttagna hästar tas bort mjukt (dold men inte raderad) så att bokningshistoriken bevaras."
        ]
      }
    ]
  },
  {
    "slug": "hitta-leverantorer",
    "title": "Hitta leverantörer",
    "role": "customer",
    "section": "Sökning",
    "keywords": [
      "leverantör",
      "sök",
      "filter",
      "betyg",
      "recensioner",
      "profil",
      "avstånd",
      "plats",
      "kompetenser",
      "öppettider"
    ],
    "summary": "Sök och filtrera bland alla aktiva tjänsteleverantörer baserat på namn, plats, betyg och tjänstetyp.",
    "content": [
      {
        "paragraphs": [
          "Gå till Leverantörer i menyn för att bläddra bland alla aktiva tjänsteleverantörer."
        ]
      },
      {
        "heading": "Du kan",
        "bullets": [
          "Söka på namn eller tjänstetyp",
          "Filtrera på plats och avstånd",
          "Sortera på högst betyg eller flest recensioner",
          "Se varje leverantörs profilbild, betyg och antal omdömen",
          "Klicka på en leverantör för att se fullständig profil"
        ]
      },
      {
        "paragraphs": [
          "Dina sökfilter sparas i URL:en, så om du klickar in på en leverantörsprofil och sedan går tillbaka bevaras dina filter."
        ]
      },
      {
        "heading": "På leverantörens profil ser du",
        "bullets": [
          "Beskrivning av verksamheten",
          "Alla tjänster med priser och tidsåtgång",
          "Öppettider per veckodag",
          "Omdömen från andra kunder",
          "Kompetenser och utbildningar med verifieringsstatus (grön badge = verifierad, grå = ej granskad) och bilder",
          "Kommande besök i ditt område"
        ]
      }
    ]
  },
  {
    "slug": "meddelanden",
    "title": "Skicka meddelande till leverantör",
    "role": "customer",
    "section": "Bokningar",
    "keywords": [
      "meddelande",
      "chatt",
      "kommunikation",
      "leverantör",
      "konversation",
      "bokning"
    ],
    "summary": "Kommunicera med din leverantör direkt i appen, kopplat till din specifika bokning.",
    "content": [
      {
        "paragraphs": [
          "Du kan kommunicera med din leverantör direkt i appen, kopplat till din specifika bokning."
        ]
      },
      {
        "heading": "Öppna konversationen",
        "steps": [
          "Gå till **Mina bokningar**",
          "Hitta den bokning du vill kommunicera om",
          "Klicka på **Meddelanden** längst ner på bokningskortet"
        ]
      },
      {
        "heading": "Skicka ett meddelande",
        "paragraphs": [
          "Skriv ditt meddelande i textfältet och klicka **Skicka**. Du kan även skicka med **Ctrl+Enter** (PC) eller **Cmd+Enter** (Mac)."
        ],
        "bullets": [
          "Maximalt 2 000 tecken per meddelande",
          "Meddelanden är kopplade till en specifik bokning"
        ]
      },
      {
        "heading": "Läsa svar",
        "paragraphs": [
          "När leverantören svarar kan du läsa svaret i samma konversationsvy. Meddelanden visas i kronologisk ordning med dina egna meddelanden till höger och leverantörens till vänster."
        ]
      }
    ]
  },
  {
    "slug": "notifikationer",
    "title": "Notifikationer",
    "role": "customer",
    "section": "Konto",
    "keywords": [
      "notifikation",
      "avisering",
      "klocka",
      "olästa",
      "e-post",
      "meddelande",
      "påminnelse"
    ],
    "summary": "Få notifikationer vid viktiga händelser som bokningsbekräftelser, betalningar och ruttannonser.",
    "content": [
      {
        "paragraphs": [
          "Du får notifikationer vid viktiga händelser. Klockikonen i menyraden visar antal olästa."
        ]
      },
      {
        "heading": "Du notifieras när",
        "bullets": [
          "Leverantören bekräftar eller avböjer din bokning",
          "En bokning markeras som genomförd",
          "Betalning har gått igenom",
          "Leverantören svarar på ditt omdöme",
          "Det är dags att boka om en tjänst (automatisk påminnelse)",
          "En leverantör annonserar en rutt i ditt område",
          "Någon går med i din grupprequest",
          "En grupprequest matchas av en leverantör"
        ]
      },
      {
        "paragraphs": [
          "Klicka på en notifikation för att komma direkt till den aktuella bokningen eller sidan. Du kan markera enskilda eller alla notifikationer som lästa.",
          "Notifikationer skickas även via e-post."
        ]
      }
    ]
  },
  {
    "slug": "recensioner",
    "title": "Recensioner",
    "role": "customer",
    "section": "Omdömen",
    "keywords": [
      "recension",
      "omdöme",
      "betyg",
      "stjärnor",
      "kommentar",
      "redigera",
      "leverantör",
      "svar"
    ],
    "summary": "Lämna omdöme med betyg och kommentar efter genomförda bokningar, och redigera eller ta bort i efterhand.",
    "content": [
      {
        "paragraphs": [
          "Efter en genomförd bokning kan du lämna ett omdöme."
        ]
      },
      {
        "heading": "Så här fungerar omdömen",
        "bullets": [
          "Ge betyg 1-5 stjärnor",
          "Skriv en valfri kommentar (max 500 tecken)",
          "Du kan redigera eller ta bort ditt omdöme i efterhand"
        ]
      },
      {
        "paragraphs": [
          "Omdömen visas publikt på leverantörens profil och hjälper andra hästägare att välja rätt leverantör. Leverantören kan svara på ditt omdöme."
        ]
      }
    ]
  },
  {
    "slug": "servicestatus",
    "title": "Servicestatus",
    "role": "customer",
    "section": "Hästar",
    "keywords": [
      "service",
      "status",
      "badge",
      "försenad",
      "snart",
      "intervall",
      "hovvård",
      "påminnelse"
    ],
    "summary": "Se automatiska statusbadges på dina hästar som visar om det är dags för service baserat på senaste bokningen.",
    "content": [
      {
        "paragraphs": [
          "På din hästlista ser du automatiskt om någon häst behöver service. Systemet beräknar detta baserat på senaste bokningens datum och tjänstens rekommenderade intervall."
        ]
      },
      {
        "heading": "Statusbadges på hästlistan",
        "bullets": [
          "Röd badge \"Försenad\" -- Hästen borde redan ha fått service",
          "Gul badge \"Snart dags\" -- Service behövs inom 2 veckor"
        ]
      },
      {
        "paragraphs": [
          "Badges visar tjänstens namn (t.ex. \"Hovvård\") så du ser vilken typ av service det gäller."
        ]
      },
      {
        "heading": "Kundstyrda serviceintervall",
        "paragraphs": [
          "Du kan själv bestämma hur ofta din häst ska få service -- oberoende av leverantörens standardintervall."
        ],
        "steps": [
          "Gå till en häst under Mina hästar",
          "Klicka på fliken Intervall",
          "Sätt intervall (i veckor) per tjänstetyp"
        ]
      },
      {
        "paragraphs": [
          "Ditt eget intervall gäller före leverantörens rekommendation och tjänstens standardvärde. Om du inte har satt ett eget intervall används leverantörens rekommendation."
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "affarsinsikter",
    "title": "Affärsinsikter",
    "role": "provider",
    "section": "Planering",
    "keywords": [
      "affärsinsikter",
      "analytics",
      "statistik",
      "populära tjänster",
      "tidsanalys",
      "kundretention",
      "avbokningsfrekvens",
      "intäkter",
      "period"
    ],
    "summary": "Analysera din verksamhets trender med diagram över populära tjänster, besökstider, kundretention och nyckeltal.",
    "content": [
      {
        "paragraphs": [
          "Under **Affärsinsikter** ser du analysdiagram och nyckeltal för din verksamhet. Använd inblicken för att planera bättre, sätta rätt priser och behålla kunder."
        ]
      },
      {
        "heading": "Välj period",
        "paragraphs": [
          "Överst på sidan väljer du analyspериod: **3 månader**, **6 månader** eller **12 månader**. Alla diagram uppdateras automatiskt."
        ]
      },
      {
        "heading": "Diagram",
        "paragraphs": [
          "### Populäraste tjänsterna",
          "Stapeldiagram som visar hur många bokningar och hur stor intäkt varje tjänst genererat under perioden. Hjälper dig se vilka tjänster som driver din verksamhet.",
          "### Besökstider (värmekarta)",
          "En värmekarta som visar vilka dagar och klockslag du har flest bokningar. Mörkare färg = fler bokningar. Användbart för att se mönster och planera ditt schema.",
          "### Kundretention",
          "Linjediagram per månad som visar:",
          "En hög andel återkommande kunder är ett tecken på nöjda kunder och stabil verksamhet."
        ],
        "bullets": [
          "**Nya kunder** -- kunder som bokade för första gången den månaden",
          "**Återkommande kunder** -- kunder som bokat tidigare"
        ]
      },
      {
        "heading": "Nyckeltal",
        "paragraphs": [
          "| Nyckeltal | Vad det mäter |",
          "|-----------|--------------|",
          "| Avbokningsfrekvens | Andel bokningar som avbokats |",
          "| No-show-frekvens | Andel kunder som inte dök upp |",
          "| Snittintäkt per bokning | Genomsnittligt belopp per genomförd bokning |",
          "| Unika kunder | Antal unika kunder under perioden |",
          "| Andel manuella bokningar | Hur stor del av bokningarna du skapat själv |"
        ]
      },
      {
        "heading": "Tips",
        "bullets": [
          "Hög no-show-frekvens? Läs om no-show-spårning i hjälpen.",
          "Många manuella bokningar? Uppmuntra kunder att boka själva via app -- sparar tid för dig.",
          "Få återkommande kunder? Kolla dina tjänsteintervall under Besöksplanering."
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "annonsera-rutter",
    "title": "Annonsera rutter",
    "role": "provider",
    "section": "Ruttplanering",
    "keywords": [
      "annonsera",
      "annonserade rutter",
      "planerade rutter",
      "kunder i området",
      "haka på"
    ],
    "summary": "Hur du annonserar planerade rutter så att kunder i området kan ansluta sig.",
    "content": [
      {
        "paragraphs": [
          "Du kan annonsera planerade rutter så att kunder i området kan ansluta sig."
        ],
        "steps": [
          "Gå till Annonserade rutter",
          "Skapa en ny annons med tjänstetyp, område och datum",
          "Kunder i området ser din annons och kan boka sig",
          "När du har tillräckligt med bokningar skapar du rutten"
        ]
      },
      {
        "paragraphs": [
          "Det här fungerar bra för t.ex. hovslagare som regelbundet besöker samma område -- kunderna kan enkelt haka på din planerade tur."
        ]
      },
      {
        "heading": "Kundupplevelsen vid annonserade rutter",
        "bullets": [
          "Kunder hittar annonserade rutter under Lediga tider i navigationen",
          "Filtrering på tjänstetyp (t.ex. skoning, verkning) via dropdown",
          "Kalendern gråar ut dagar utanför annonsperioden så kunden ser tillgängliga datum",
          "Vid bokning väljer kunden häst via en dropdown istället för fritext",
          "Tjänster visas med pris direkt på service-chips",
          "Bokningar gjorda via en annonserad rutt visas med en \"Via rutt\"-badge i kundens bokningslista"
        ]
      }
    ]
  },
  {
    "slug": "aterkommande-bokningar",
    "title": "Återkommande bokningar",
    "role": "provider",
    "section": "Bokningar",
    "keywords": [
      "återkommande",
      "serie",
      "intervall",
      "max tillfällen",
      "upprepning",
      "regelbundna"
    ],
    "summary": "Hur du aktiverar återkommande bokningar, sätter max antal tillfällen och skapar serier åt kunder.",
    "content": [
      {
        "paragraphs": [
          "Som leverantör bestämmer du om dina kunder ska kunna skapa återkommande bokningar, och hur långa serier de får skapa."
        ]
      },
      {
        "heading": "Aktivera återkommande bokningar",
        "steps": [
          "Gå till Min profil",
          "Slå på \"Tillåt återkommande bokningar\"",
          "Välj \"Max antal tillfällen per serie\" -- det högsta antal bokningar en kund kan skapa i en serie"
        ]
      },
      {
        "paragraphs": [
          "Tillgängliga max-värden: 4, 6, 8, 12, 24 eller 52 tillfällen.",
          "Inställningen sparas direkt och gäller för alla nya bokningsserier. Befintliga serier påverkas inte."
        ]
      },
      {
        "heading": "Skapa serie via manuell bokning",
        "paragraphs": [
          "Du kan också skapa återkommande bokningar åt kunder via Ny bokning i kalendervyn:"
        ],
        "steps": [
          "Fyll i bokningsuppgifterna som vanligt (kund, tjänst, datum, tid)",
          "Slå på \"Gör detta återkommande\"",
          "Välj intervall och antal tillfällen",
          "Bekräfta -- alla bokningar i serien skapas automatiskt"
        ]
      },
      {
        "heading": "Serie i kalendern",
        "paragraphs": [
          "Bokningar som tillhör en serie markeras med en upprepningsikon i kalendern. Hovra över ikonen för att se \"Återkommande bokning\".",
          "Varje bokning i serien hanteras individuellt -- du kan bekräfta, genomföra eller avboka enskilda bokningar utan att påverka resten av serien."
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "besoksplanering",
    "title": "Besöksplanering",
    "role": "provider",
    "section": "Planering",
    "keywords": [
      "besöksplanering",
      "försenad",
      "återbesök",
      "intervall",
      "due-for-service",
      "hästar",
      "planering"
    ],
    "summary": "Hur du ser vilka hästar som snart behöver besök och planerar ditt schema utifrån angelägenhet.",
    "content": [
      {
        "paragraphs": [
          "Under Besöksplanering ser du vilka hästar som snart behöver besök, sorterade efter angelägenhet. Det hjälper dig att planera ditt schema och aldrig missa en kund."
        ]
      },
      {
        "heading": "Varje häst visas med",
        "bullets": [
          "Hästnamn och ägare",
          "Vilken tjänst som utfördes",
          "Antal dagar sedan senaste besök",
          "Återbesöksintervall (i veckor)",
          "Beräknat nästa besöksdatum",
          "Statusbadge"
        ]
      },
      {
        "heading": "Statusbadges",
        "bullets": [
          "Röd (Försenad) -- Besöket borde redan ha skett",
          "Gul (Inom 2 veckor) -- Dags att planera in besöket",
          "Grön (Ej aktuell) -- Inget besök behövs ännu"
        ]
      },
      {
        "heading": "Filtrering",
        "bullets": [
          "Alla -- visa samtliga hästar med återbesöksintervall",
          "Försenade -- enbart hästar som passerat sitt datum",
          "Inom 2 veckor -- hästar som snart behöver besök"
        ]
      },
      {
        "heading": "Individuella intervall per häst och tjänst",
        "paragraphs": [
          "Standardintervallet sätts på tjänstenivå (t.ex. 8 veckor för hovbeläggning). Men ibland behöver en specifik häst tätare -- eller glesare -- besök. Du kan sätta individuella intervall per häst och per tjänst.",
          "Gå till Hästens hälsohistorik (klicka på en häst) och tryck Lägg till under Återbesöksintervall. Välj tjänst, välj intervall och spara. Du kan ha olika intervall för olika tjänster på samma häst -- t.ex. 6 veckor för hovslagning och 8 veckor för massage.",
          "Det individuella intervallet gäller bara för dig som leverantör. Kunden kan också ha satt ett eget intervall som har högre prioritet (prioritetsordning: Kundens intervall > Leverantörens intervall > Tjänstens standard)."
        ]
      }
    ]
  },
  {
    "slug": "bjud-in-kund",
    "title": "Bjud in manuell kund",
    "role": "provider",
    "section": "Kunder",
    "keywords": [
      "bjud in",
      "inbjudan",
      "spökkund",
      "aktivera konto",
      "e-post",
      "aktiveringslänk"
    ],
    "summary": "Hur du bjuder in manuellt tillagda kunder att skapa ett riktigt konto via e-postinbjudan.",
    "content": [
      {
        "paragraphs": [
          "Manuellt tillagda kunder (så kallade \"spökkunder\") har inget riktigt konto -- de kan inte logga in, boka själva eller se sin hälsotidslinje. Du kan bjuda in dem att skapa ett konto."
        ]
      },
      {
        "heading": "Krav",
        "bullets": [
          "Kunden måste ha en giltig e-postadress registrerad"
        ]
      },
      {
        "heading": "Så här gör du",
        "steps": [
          "Gå till Kunder i leverantörsmenyn",
          "Klicka på den manuellt tillagda kunden",
          "Klicka Skicka inbjudan",
          "Kunden får ett e-postmeddelande med en aktiveringslänk",
          "Kunden klickar på länken och sätter ett lösenord",
          "Kontot aktiveras -- kunden kan nu logga in och boka själv"
        ]
      },
      {
        "heading": "Bra att veta",
        "bullets": [
          "Inbjudningslänken är giltig i 48 timmar",
          "Om kunden inte aktiverar i tid kan du skicka en ny inbjudan",
          "Kundens bokningshistorik och hästkopplingar bevaras vid aktiveringen"
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "bokforing-fortnox",
    "title": "Bokföring (Fortnox)",
    "role": "provider",
    "section": "Integrationer",
    "keywords": [
      "bokföring",
      "Fortnox",
      "faktura",
      "integration",
      "OAuth",
      "synkning"
    ],
    "summary": "Hur du kopplar ditt Fortnox-konto för automatisk fakturering av genomförda bokningar.",
    "content": [
      {
        "paragraphs": [
          "Du kan koppla ditt Fortnox-konto för automatisk fakturering."
        ],
        "steps": [
          "Gå till Inställningar i leverantörsmenyn",
          "Klicka Koppla Fortnox",
          "Logga in med ditt Fortnox-konto (OAuth)",
          "Equinet kan nu skapa fakturor i Fortnox"
        ]
      },
      {
        "heading": "Funktioner",
        "bullets": [
          "Manuell synkning av osynkade bokningar till Fortnox-fakturor",
          "Automatisk token-förnyelse (du behöver inte logga in igen)",
          "Du kan koppla bort Fortnox när som helst"
        ]
      },
      {
        "paragraphs": [
          "Tokens lagras krypterat. Under utveckling/demo används en mock-implementation."
        ]
      }
    ]
  },
  {
    "slug": "demo-guide",
    "title": "Demo-guide — Erik Järnfot",
    "role": "provider",
    "section": "Demo",
    "keywords": [
      "demo",
      "walkthrough",
      "guide",
      "erik järnfot",
      "järnfots hovslageri"
    ],
    "summary": "Steg-för-steg genomgång av demoläget för Erik Järnfot, Järnfots Hovslageri.",
    "content": [
      {
        "paragraphs": [
          "Rekommenderad ordning för att visa plattformen för en pilot-leverantör."
        ]
      },
      {
        "heading": "Inloggning",
        "paragraphs": [
          "Logga in som **Erik Järnfot** på `/login`:"
        ],
        "bullets": [
          "E-post: `erik.jarnfot@demo.equinet.se`",
          "Lösenord: `DemoProvider123!`"
        ]
      },
      {
        "heading": "Genomgång (10 steg)",
        "bullets": [
          "**Dashboard** — översikt bokningar, kunder, aktuella händelser",
          "**Kalender** — veckovy, klicka på Lisa Andersson/Molly-bokningen",
          "**Bokningsdetalj** — serie-badge (\"Del av återkommande serie\"), kundinfo, tidslinje",
          "**Bokningslista** — filtrera per status, se historik",
          "**Kundlista** — klicka på Anders Bergman",
          "**Kunddetalj Anders Bergman** — öppna Meddelanden-fliken, visa Smart Reply-chips. Klicka \"Jag är framme nu!\" — textrutan fylls i automatiskt med datum, tid och telefon",
          "**Kunddetalj Lisa Andersson** — visa hästar, anteckningar, \"Bjud in kund\"-knappen",
          "**Affärsinsikter** — grafer för bokningar, intäkter, populäraste tjänster",
          "**Tjänster** — visa och redigera en tjänst med rekommenderat intervall",
          "**Profil** — leverantörsprofil, inställningar, återkommande bokningar-toggle"
        ]
      },
      {
        "heading": "Bra poänger att lyfta",
        "bullets": [
          "**Smart Replies** — svara kunder med ett klick, mallar fylls i automatiskt med datum, tid och telefon",
          "**Återkommande bokningar** — seriebaserade med automatisk schemaläggning (8-veckorsintervall)",
          "**Affärsinsikter** — intäkter, populäraste tjänster och populäraste tider",
          "**Kundinbjudningar** — bjud in kunder via e-post direkt från kundkortet",
          "**Due-for-service** — kunder vars hästar är försenade med hovvård visas på dashboard",
          "**Manuell bokning** — leverantören kan lägga in bokningar för kunder",
          "**Kundanteckningar** — privata journalanteckningar per kund, aldrig synliga för kunden",
          "**Recensioner** — kundernas omdömen samlade under profilen"
        ]
      }
    ]
  },
  {
    "slug": "foretagsprofil",
    "title": "Företagsprofil",
    "role": "provider",
    "section": "Profil",
    "keywords": [
      "profil",
      "företagsprofil",
      "profilbild",
      "företagsnamn",
      "beskrivning",
      "adress",
      "serviceområde",
      "bokningsinställningar"
    ],
    "summary": "Så fyller du i och hanterar din företagsprofil med kontaktuppgifter, serviceområde och bokningsinställningar.",
    "content": [
      {
        "paragraphs": [
          "Under Min profil finns tre flikar:"
        ]
      },
      {
        "heading": "Profil-fliken",
        "bullets": [
          "Profilbild -- ladda upp en bild som visas för kunder (dra och släpp eller klicka)",
          "Företagsnamn -- det namn kunder ser",
          "Beskrivning -- berätta om din verksamhet och erfarenhet",
          "Adress, ort, postnummer -- din utgångspunkt (används för avståndberäkning)",
          "Serviceområde -- hur långt du åker (standard 50 km radie)"
        ]
      },
      {
        "heading": "Tillgänglighet-fliken",
        "bullets": [
          "Veckoschema och tillgänglighetsundantag",
          "Kompetenser & verifiering"
        ]
      },
      {
        "heading": "Bokningsinställningar-fliken",
        "bullets": [
          "Bokningsinställningar (acceptera nya kunder, etc.)",
          "Ombokning och återkommande bokningar"
        ]
      },
      {
        "paragraphs": [
          "Adressen omvandlas automatiskt till GPS-koordinater som används vid ruttplanering och restidsberäkning."
        ]
      }
    ]
  },
  {
    "slug": "genomfora-en-rutt",
    "title": "Genomföra en rutt",
    "role": "provider",
    "section": "Ruttplanering",
    "keywords": [
      "genomföra rutt",
      "starta rutt",
      "steg-för-steg",
      "stopp",
      "Google Maps",
      "vägbeskrivning"
    ],
    "summary": "Hur du följer och genomför en rutt steg för steg med statushantering för varje stopp.",
    "content": [
      {
        "paragraphs": [
          "När du startar en rutt får du en steg-för-steg-vy."
        ]
      },
      {
        "heading": "För varje stopp kan du",
        "bullets": [
          "Se kundinformation, adress och tjänst",
          "Öppna vägbeskrivning i Google Maps",
          "Markera ankomst och avgång",
          "Rapportera problem (med kommentar)",
          "Markera stoppet som genomfört"
        ]
      },
      {
        "heading": "Stoppstatus",
        "bullets": [
          "Planerat (inte påbörjat)",
          "Pågår (du är på plats)",
          "Genomfört",
          "Problem (med anteckning)"
        ]
      },
      {
        "paragraphs": [
          "Systemet beräknar automatiskt uppskattad ankomsttid till nästa stopp."
        ]
      }
    ]
  },
  {
    "slug": "gruppbokning",
    "title": "Gruppbokning",
    "role": "provider",
    "section": "Bokningar",
    "keywords": [
      "gruppbokning",
      "grupprequest",
      "stall",
      "stallgemenskap",
      "matcha",
      "deltagare"
    ],
    "summary": "Hur du ser och matchar grupprequests från stallgemenskaper i ditt serviceområde.",
    "content": [
      {
        "paragraphs": [
          "Under Grupprequests ser du öppna grupprequests från stallgemenskaper i ditt serviceområde."
        ]
      },
      {
        "heading": "För varje request ser du",
        "bullets": [
          "Tjänstetyp, plats och önskat datumintervall",
          "Antal deltagare och deras hästar",
          "Kontaktperson"
        ]
      },
      {
        "heading": "Matcha en grupprequest",
        "steps": [
          "Välj en öppen grupprequest",
          "Systemet skapar automatiskt individuella bokningar för alla deltagare i sekvens (t.ex. 09:00, 09:45, 10:30)",
          "Alla deltagare notifieras med sin individuella tid"
        ]
      },
      {
        "paragraphs": [
          "Det här är ett effektivt sätt att fylla en halv- eller heldag med bokningar på samma plats."
        ]
      }
    ]
  },
  {
    "slug": "hantera-bokningar",
    "title": "Hantera bokningar",
    "role": "provider",
    "section": "Bokningar",
    "keywords": [
      "bokningar",
      "acceptera",
      "avböja",
      "genomförd",
      "avbokad",
      "väntande",
      "bekräftad",
      "leverantörsanteckningar"
    ],
    "summary": "Hur du hanterar inkommande och befintliga bokningar med statusar, detaljer och leverantörsanteckningar.",
    "content": [
      {
        "paragraphs": [
          "Under Bokningar ser du alla inkommande och befintliga bokningar."
        ]
      },
      {
        "heading": "Statusar",
        "bullets": [
          "Väntande -- Acceptera eller avböj (med anledning)",
          "Bekräftad -- Utför tjänsten, markera sedan som genomförd",
          "Genomförd -- Klar, kunden kan nu betala och lämna omdöme",
          "Ej infunnit -- Kunden infann sig inte",
          "Avbokad -- Avbokad av kund eller dig"
        ]
      },
      {
        "heading": "För varje bokning ser du",
        "bullets": [
          "Kundens namn och kontaktuppgifter",
          "Tjänst, datum, tid",
          "Hästinformation och eventuella kundkommentarer"
        ]
      },
      {
        "heading": "Leverantörsanteckningar",
        "paragraphs": [
          "På bekräftade och genomförda bokningar kan du skriva egna anteckningar -- till exempel vad du observerade, vilken behandling du gav, eller vad som bör följas upp nästa gång."
        ],
        "steps": [
          "Klicka på en bokning i kalendern för att öppna bokningsdetaljen",
          "Skriv din anteckning i textfältet \"Leverantörsanteckningar\"",
          "Klicka Spara (eller Rensa för att ta bort)"
        ]
      },
      {
        "paragraphs": [
          "Dina anteckningar är bara synliga för dig. Kunden ser dem inte, och de visas inte i hästpasset eller andra publika vyer. Anteckningarna visas även i hästens hälsotidslinje så att du kan se dina tidigare observationer inför nästa besök."
        ]
      }
    ]
  },
  {
    "slug": "hantera-tjanster",
    "title": "Hantera tjänster",
    "role": "provider",
    "section": "Tjänster",
    "keywords": [
      "tjänster",
      "pris",
      "tid",
      "hovbeläggning",
      "akupunktur",
      "återbesöksintervall",
      "inaktivera"
    ],
    "summary": "Så lägger du till, redigerar och hanterar de tjänster du erbjuder.",
    "content": [
      {
        "paragraphs": [
          "Under Mina tjänster lägger du till de tjänster du erbjuder."
        ]
      },
      {
        "heading": "För varje tjänst anger du",
        "bullets": [
          "Namn (t.ex. \"Hovbeläggning\", \"Akupunktur\")",
          "Beskrivning",
          "Pris i kronor",
          "Tidsåtgång i minuter",
          "Rekommenderat återbesöksintervall (i veckor) -- t.ex. 8 veckor för hovbeläggning"
        ]
      },
      {
        "paragraphs": [
          "Återbesöksintervallet gör att systemet automatiskt påminner kunden när det är dags att boka igen. Detta genererar återkommande bokningar utan att du behöver följa upp manuellt.",
          "Du kan aktivera och inaktivera tjänster. Inaktiva tjänster visas inte för kunder."
        ]
      }
    ]
  },
  {
    "slug": "hastens-halsotidslinje",
    "title": "Hästens hälsotidslinje",
    "role": "provider",
    "section": "Hästar",
    "keywords": [
      "hälsotidslinje",
      "häst",
      "veterinär",
      "hovvård",
      "skador",
      "medicinering",
      "historik"
    ],
    "summary": "Hur du ser hälsotidslinjen för hästar kopplade till dina bokningar med veterinär- och hovvårdshistorik.",
    "content": [
      {
        "paragraphs": [
          "Som leverantör kan du se en begränsad hälsotidslinje för hästar som är kopplade till dina bokningar. Det ger dig viktig kontext inför ett besök."
        ]
      },
      {
        "heading": "Du ser",
        "bullets": [
          "Veterinärhistorik",
          "Hovvårdshistorik",
          "Skadehistorik",
          "Medicineringshistorik",
          "Dina egna leverantörsanteckningar (kopplade till respektive bokning)"
        ]
      },
      {
        "paragraphs": [
          "Du ser inte ägarens privata anteckningar (kategorin \"Övrigt\").",
          "Informationen är skrivskyddad -- du kan inte redigera kundens anteckningar."
        ]
      }
    ]
  },
  {
    "slug": "installera-equinet",
    "title": "Installera Equinet som app",
    "role": "provider",
    "section": "Konto",
    "keywords": [
      "installera",
      "app",
      "PWA",
      "hemskärm",
      "Android",
      "iPhone",
      "iPad",
      "Safari",
      "Chrome"
    ],
    "summary": "Hur du installerar Equinet som app på din hemskärm för snabbare åtkomst och offline-stöd.",
    "content": [
      {
        "paragraphs": [
          "Du kan installera Equinet på din hemskärm för snabbare åtkomst och offline-stöd. En installerad app öppnas i helskärm utan webbläsarens adressfält."
        ]
      },
      {
        "heading": "Android (Chrome)",
        "steps": [
          "Besök Equinet i Chrome",
          "En blå banner visas med knappen Installera -- klicka på den",
          "Bekräfta installationen",
          "Equinet-ikonen visas på din hemskärm"
        ]
      },
      {
        "heading": "iPhone/iPad (Safari)",
        "steps": [
          "Besök Equinet i Safari",
          "En blå banner visas med instruktioner",
          "Tryck på Dela-ikonen (rutan med uppåtpilen)",
          "Välj Lägg till på hemskärmen",
          "Klicka Lägg till"
        ]
      },
      {
        "paragraphs": [
          "Du kan stänga installationsbannern om du inte vill installera. Den visas inte igen efter att du stängt den."
        ]
      },
      {
        "heading": "iOS-app (native)",
        "paragraphs": [
          "Det finns också en separat Equinet-app för iPhone byggd med native SwiftUI. Den ger:",
          "Fråga din kontakt på Equinet om tillgänglighet och installation av native iOS-appen."
        ],
        "bullets": [
          "Native dashboard, kalender, bokningslista och kundhantering",
          "Push-notiser via APNs (bekräfta och avvisa bokningar direkt från notisen)",
          "Synkronisering med iOS Kalender -- bekräftade bokningar hamnar automatiskt i din kalender (Apple Watch-påminnelser och Siri-förslag inkluderat)",
          "Widget på hemskärmen som visar din nästa bokning",
          "Native taligenkänning för röstloggning",
          "Offline-detektion och amber/grön återanslutningsbanner"
        ]
      }
    ]
  },
  {
    "slug": "komma-igang",
    "title": "Komma igång som leverantör",
    "role": "provider",
    "section": "Kom igång",
    "keywords": [
      "komma igång",
      "starta",
      "checklista",
      "ny leverantör",
      "uppsättning",
      "setup",
      "registrera"
    ],
    "summary": "Steg-för-steg-checklista för att komma igång som leverantör på Equinet.",
    "content": [
      {
        "paragraphs": [
          "När du skapar ett leverantörskonto möts du av en checklista på din dashboard som vägleder dig genom uppsättningen."
        ],
        "steps": [
          "Fyll i din företagsprofil",
          "Lägg till minst en tjänst",
          "Ställ in dina öppettider",
          "Verifiera din e-postadress",
          "(Valfritt) Ansök om verifiering"
        ]
      },
      {
        "paragraphs": [
          "Du ser din framgång som en procent-indikator. När alla steg är klara är du redo att ta emot bokningar."
        ]
      }
    ]
  },
  {
    "slug": "kompetenser-och-verifiering",
    "title": "Kompetenser och verifiering",
    "role": "provider",
    "section": "Profil",
    "keywords": [
      "kompetenser",
      "verifiering",
      "utbildning",
      "certifikat",
      "licens",
      "organisation",
      "badge",
      "bilder"
    ],
    "summary": "Hur du lägger till utbildningar, certifikat och andra meriter som visas på din profil.",
    "content": [
      {
        "paragraphs": [
          "Under Kompetenser & Verifiering lägger du till dina utbildningar, certifikat och meriter. Godkända kompetenser visas på din profil och stärker förtroendet hos potentiella kunder."
        ]
      },
      {
        "heading": "Kompetenstyper",
        "bullets": [
          "Utbildning -- formell utbildning (t.ex. \"Wångens gesällprov\")",
          "Organisation -- medlemskap i branschorganisation",
          "Certifikat -- godkänt certifieringsprov (t.ex. \"EHB-certifikat\")",
          "Erfarenhet -- arbetserfarenhet och referenser",
          "Licens -- yrkeslicens (t.ex. veterinärlicens)"
        ]
      },
      {
        "heading": "Lägg till en kompetens",
        "steps": [
          "Gå till Kompetenser & Verifiering i leverantörsmenyn",
          "Klicka Ny kompetens",
          "Välj typ och fyll i titel (obligatoriskt)",
          "Ange utfärdare (t.ex. \"Wången\", \"SHF\") och år -- valfritt men rekommenderas",
          "Lägg till en beskrivning om du vill",
          "Skicka in"
        ]
      },
      {
        "heading": "Ladda upp bilder",
        "paragraphs": [
          "Efter att du skapat en kompetenspost kan du ladda upp bilder som styrker din merit -- till exempel diplom, certifikat eller intyg."
        ],
        "bullets": [
          "Dra och släpp eller klicka för att ladda upp",
          "Max 5 bilder per kompetenspost",
          "Bilder komprimeras automatiskt (max 1 MB)",
          "Du kan ta bort bilder genom att hovra och klicka krysset"
        ]
      },
      {
        "paragraphs": [
          "Bilder kan bara laddas upp och tas bort på poster som inte är godkända."
        ]
      },
      {
        "heading": "Redigera och ta bort",
        "paragraphs": [
          "Du kan redigera och ta bort kompetenser som har status \"Under granskning\" eller \"Avvisad\"."
        ],
        "bullets": [
          "Klicka Redigera för att uppdatera titel, typ, utfärdare, år eller beskrivning",
          "Om en avvisad kompetens redigeras återgår den automatiskt till granskning",
          "Klicka Ta bort för att radera en kompetens och alla tillhörande bilder (kräver bekräftelse)",
          "Godkända kompetenser kan inte redigeras eller tas bort"
        ]
      },
      {
        "heading": "Statusar",
        "bullets": [
          "Under granskning -- En administratör har inte granskat ännu",
          "Godkänd -- Kompetensen är verifierad och visas med grön badge på din profil",
          "Avvisad -- Administratören behöver mer information (se granskningskommentaren)"
        ]
      },
      {
        "paragraphs": [
          "Du kan ha max 5 kompetenser under granskning samtidigt. Vänta tills befintliga har granskats innan du skickar fler."
        ]
      },
      {
        "heading": "Vad ser kunder?",
        "paragraphs": [
          "På din profil ser kunder en sektion \"Kompetenser & Utbildningar\" med:"
        ],
        "bullets": [
          "Titel, typ, utfärdare och år",
          "Grön badge \"Verifierad\" för godkända kompetenser",
          "Grå badge \"Ej granskad\" för poster under granskning",
          "Klickbara bilder (öppnas i förstoring)",
          "Avvisade kompetenser visas inte för kunder"
        ]
      }
    ]
  },
  {
    "slug": "kundanteckningar",
    "title": "Kundanteckningar",
    "role": "provider",
    "section": "Kunder",
    "keywords": [
      "anteckningar",
      "kundanteckningar",
      "journal",
      "privat",
      "redigera",
      "ta bort"
    ],
    "summary": "Hur du skriver, redigerar och tar bort privata anteckningar om dina kunder.",
    "content": [
      {
        "paragraphs": [
          "Under varje kund i kundregistret kan du skriva privata anteckningar -- en slags journal."
        ]
      },
      {
        "heading": "Skapa anteckning",
        "steps": [
          "Klicka på en kund i kundregistret",
          "Skriv din anteckning i textfältet",
          "Klicka Spara"
        ]
      },
      {
        "heading": "Redigera anteckning",
        "bullets": [
          "Klicka pennikonen bredvid anteckningen",
          "Uppdatera texten",
          "Klicka Spara",
          "Redigerade anteckningar markeras med \"(redigerad)\""
        ]
      },
      {
        "heading": "Ta bort anteckning",
        "bullets": [
          "Klicka papperskorgen bredvid anteckningen"
        ]
      },
      {
        "paragraphs": [
          "Dina anteckningar är bara synliga för dig. Kunden ser dem inte, och de visas inte i hästprofilen eller andra publika vyer."
        ]
      }
    ]
  },
  {
    "slug": "kundinsikter",
    "title": "Kundinsikter",
    "role": "provider",
    "section": "Kunder",
    "keywords": [
      "kundinsikter",
      "AI",
      "VIP-score",
      "besöksfrekvens",
      "riskflaggor",
      "mönster",
      "insikter"
    ],
    "summary": "Hur du använder AI-drivna insikter för att förstå dina kunders beteende och värde.",
    "content": [
      {
        "paragraphs": [
          "Under varje kund i kundregistret kan du generera AI-drivna insikter som hjälper dig förstå kunden bättre."
        ]
      },
      {
        "heading": "Klicka \"Generera insikter\" för att se",
        "bullets": [
          "VIP-score -- hur värdefull kunden är (baserat på frekvens, intäkt, lojalitet)",
          "Besöksfrekvens -- genomsnittligt intervall mellan bokningar",
          "Riskflaggor -- varning om kunden visar tecken på att sluta boka (t.ex. ökande intervall, avbokningar)",
          "Mönster -- insikter om kundens beteende (föredragen dag, tjänst, etc.)"
        ]
      },
      {
        "heading": "Viktigt att veta",
        "bullets": [
          "Insikterna baseras på bokningshistorik, inte personlig data",
          "En confidence-indikator visar hur säkra insikterna är (fler bokningar = mer tillförlitligt)",
          "Insikterna genereras on-demand och cachas inte"
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "kundrecensioner",
    "title": "Kundrecensioner",
    "role": "provider",
    "section": "Omdömen",
    "keywords": [
      "kundrecension",
      "betygsätt kund",
      "stjärnor",
      "privat",
      "kundomdöme"
    ],
    "summary": "Hur du betygsätter dina kunder med stjärnor och kommentarer som bara du kan se.",
    "content": [
      {
        "paragraphs": [
          "Som leverantör kan du också betygsätta dina kunder. Det hjälper dig att komma ihåg upplevelser och planera framtida besök."
        ]
      },
      {
        "heading": "Lämna en kundrecension",
        "steps": [
          "Gå till en genomförd bokning",
          "Klicka Betygsätt kund",
          "Ge 1-5 stjärnor",
          "Skriv en valfri kommentar"
        ]
      },
      {
        "paragraphs": [
          "Kundrecensioner är bara synliga för dig. Kunden ser inte betyget eller kommentaren."
        ]
      }
    ]
  },
  {
    "slug": "kundregister",
    "title": "Kundregister",
    "role": "provider",
    "section": "Kunder",
    "keywords": [
      "kundregister",
      "kunder",
      "kundlista",
      "aktiva",
      "inaktiva",
      "sök kund",
      "hästar"
    ],
    "summary": "Hur du använder kundregistret för att se, filtrera och söka bland dina kunder.",
    "content": [
      {
        "paragraphs": [
          "Under Kunder i leverantörsmenyn hittar du en samlad översikt över alla dina kunder."
        ]
      },
      {
        "heading": "Listan visar",
        "bullets": [
          "Kundens namn, e-post och telefon",
          "Antal genomförda bokningar",
          "Datum för senaste bokning",
          "Kundens registrerade hästar"
        ]
      },
      {
        "heading": "Filtrera och sök",
        "bullets": [
          "Alla -- visa samtliga kunder",
          "Aktiva -- kunder med bokning senaste 12 månaderna",
          "Inaktiva -- kunder utan bokning senaste 12 månaderna",
          "Fritextsök -- sök på namn eller e-postadress"
        ]
      },
      {
        "paragraphs": [
          "Klicka på en kund för att visa detaljerad information och en lista på kundens hästar.",
          "Kundlistan bygger automatiskt upp sig från genomförda bokningar, men du kan även lägga till kunder manuellt."
        ]
      }
    ]
  },
  {
    "slug": "manuell-bokning",
    "title": "Manuell bokning",
    "role": "provider",
    "section": "Bokningar",
    "keywords": [
      "manuell bokning",
      "skapa bokning",
      "boka åt kund",
      "kalender",
      "ny bokning",
      "ringer"
    ],
    "summary": "Hur du skapar bokningar åt kunder direkt från kalendervyn, till exempel när en kund ringer.",
    "content": [
      {
        "paragraphs": [
          "Du kan skapa bokningar åt kunder direkt från kalendervyn -- till exempel när en kund ringer och vill boka."
        ],
        "steps": [
          "Klicka på en dag i Kalendern",
          "Klicka Ny bokning",
          "Sök efter en befintlig kund (bland dina tidigare kunder) eller ange namn och telefonnummer för en ny kund",
          "Välj tjänst och tid från en dropdown med lediga 15-minutersintervall",
          "Välj häst (om kunden har registrerade hästar) eller ange hästinformation manuellt",
          "Bekräfta"
        ]
      },
      {
        "paragraphs": [
          "Manuellt skapade bokningar markeras med ett \"M\" i kalendern så du kan skilja dem från kundinitierade bokningar. De bekräftas automatiskt (hoppar över \"väntar på svar\"-steget)."
        ]
      }
    ]
  },
  {
    "slug": "manuell-kundregistrering",
    "title": "Manuell kundregistrering",
    "role": "provider",
    "section": "Kunder",
    "keywords": [
      "manuell kund",
      "lägg till kund",
      "registrera kund",
      "kundregistrering"
    ],
    "summary": "Hur du lägger till kunder manuellt i kundregistret utan att de behöver ha bokat via plattformen.",
    "content": [
      {
        "paragraphs": [
          "Du kan lägga till kunder direkt i kundregistret utan att de behöver ha bokat via plattformen."
        ],
        "steps": [
          "Gå till Kunder i leverantörsmenyn",
          "Klicka Lägg till kund",
          "Fyll i namn (obligatoriskt), telefon och e-post (valfritt)",
          "Klicka Spara"
        ]
      },
      {
        "paragraphs": [
          "Manuellt tillagda kunder visas i kundregistret med samma funktioner som bokningsgenererade kunder. Du kan ta bort en manuellt tillagd kund via kuvert-ikonen."
        ]
      }
    ]
  },
  {
    "slug": "meddelanden",
    "title": "Meddelanden",
    "role": "provider",
    "section": "Dagligt arbete",
    "keywords": [
      "meddelanden",
      "inkorg",
      "konversation",
      "kund",
      "chatt",
      "kommunikation",
      "olästa",
      "badge",
      "snabbsvar"
    ],
    "summary": "Läs och svara på kundmeddelanden direkt i Equinet.",
    "content": [
      {
        "paragraphs": [
          "# Meddelanden",
          "Med Meddelanden-funktionen kan du och dina kunder kommunicera direkt kring en specifik bokning utan att behöva byta till e-post eller SMS."
        ]
      },
      {
        "heading": "Inkorg",
        "paragraphs": [
          "Du hittar din inkorg via **Meddelanden**-fliken i navigeringen. Inkorgen visar alla aktiva konversationer, sorterade med olästa meddelanden överst.",
          "Varje rad visar:"
        ],
        "bullets": [
          "Kundens namn och tjänst",
          "Bokningsdatum",
          "Senaste meddelandet",
          "Rött oläst-märke med antal olästa"
        ]
      },
      {
        "heading": "Öppna en konversation",
        "paragraphs": [
          "Klicka på en rad för att öppna tråden. Alla meddelanden från kunden och dina egna svar visas i kronologisk ordning. Olästa meddelanden markeras automatiskt som lästa när du öppnar tråden."
        ]
      },
      {
        "heading": "Svara på ett meddelande",
        "paragraphs": [
          "Skriv ditt svar i textfältet längst ned och klicka **Skicka**, eller tryck **Ctrl+Enter** (Windows) / **Cmd+Enter** (Mac)."
        ]
      },
      {
        "heading": "Oläst-badge i navigeringen",
        "paragraphs": [
          "Om du har olästa meddelanden visas ett rött märke med antal på Meddelanden-ikonen i navigeringen. Märket uppdateras automatiskt var 30:e sekund."
        ]
      },
      {
        "heading": "Snabbsvar",
        "paragraphs": [
          "Ovanför skriv-fältet visas 4 klickbara snabbsvar:",
          "Klicka för att fylla i textrutan — du kan redigera innan du skickar."
        ],
        "bullets": [
          "\"Bokningen är bekräftad. Vi ses [datum] kl [tid].\"",
          "\"Tack! Jag återkommer så snart jag kan.\"",
          "\"Ring mig på [ditt telefonnummer] om det brådskar.\"",
          "\"Vilken tid passar dig istället?\""
        ]
      },
      {
        "heading": "Tips",
        "bullets": [
          "Meddelanden är kopplade till en specifik bokning — du och kunden ser bara meddelanden för den gemensamma bokningen.",
          "Kunden kan initiera en konversation från sin bokningssida. Du svarar i din inkorg.",
          "Funktionen kräver att Meddelanden är aktiverat i ditt konto. Kontakta support om du inte ser fliken."
        ]
      }
    ]
  },
  {
    "slug": "notifikationer",
    "title": "Notifikationer",
    "role": "provider",
    "section": "Konto",
    "keywords": [
      "notifikationer",
      "aviseringar",
      "klocka",
      "e-post",
      "bokning",
      "omdöme",
      "grupprequest"
    ],
    "summary": "Vilka notifikationer du får som leverantör och var de visas.",
    "content": [
      {
        "paragraphs": [
          "Du får notifikationer vid viktiga händelser."
        ]
      },
      {
        "heading": "Du notifieras när",
        "bullets": [
          "En kund bokar en tjänst hos dig",
          "En kund avbokar",
          "En kund betalar",
          "En kund lämnar ett omdöme",
          "En verifieringsansökan godkänns eller avvisas",
          "En ny grupprequest skapas i ditt område"
        ]
      },
      {
        "paragraphs": [
          "Notifikationer visas i klockan i menyraden och skickas även via e-post."
        ]
      }
    ]
  },
  {
    "slug": "offline-lage",
    "title": "Offline-läge",
    "role": "provider",
    "section": "Konto",
    "keywords": [
      "offline",
      "utan nät",
      "synka",
      "sparad lokalt",
      "mobilnät",
      "återansluten",
      "banner"
    ],
    "summary": "Hur offline-läget fungerar så att du kan använda Equinet utan internetanslutning.",
    "content": [
      {
        "paragraphs": [
          "Om du kör i ett område utan mobilnät kan du fortfarande använda Equinet tack vare offline-stöd. Du kan både se och göra ändringar -- ändringarna sparas lokalt och synkas automatiskt när du får nät igen."
        ]
      },
      {
        "heading": "Så fungerar det",
        "bullets": [
          "När du har internetåtkomst sparas dina bokningar, rutter och profildata automatiskt lokalt på enheten",
          "Om du tappar nätverket visar Equinet den senast sparade datan",
          "En gul banner visas längst upp på sidan med texten \"Du är offline\"",
          "När nätverket kommer tillbaka visas en grön banner med \"Återansluten\" och antal synkade ändringar"
        ]
      },
      {
        "heading": "Ändringar offline",
        "bullets": [
          "Du kan markera bokningar som klara -- bokningen uppdateras direkt i appen",
          "Du kan uppdatera anteckningar på bokningar",
          "Du kan ändra status på ruttstopp (markera som besökt)",
          "Ändringar som väntar på synk visas med en gul badge (\"Väntar på synk\")",
          "Vid återanslutning synkas alla ändringar automatiskt i bakgrunden"
        ]
      },
      {
        "heading": "Begränsningar i offline-läge",
        "bullets": [
          "Data som är äldre än 4 timmar visas inte (du uppmanas att ansluta igen)",
          "Funktioner som kräver nätverksåtkomst (betala, boka nya tider, skicka meddelanden) fungerar inte offline",
          "Om en annan person ändrar samma bokning medan du är offline gäller den senaste ändringen"
        ],
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "recensioner-och-betyg",
    "title": "Recensioner och betyg",
    "role": "provider",
    "section": "Omdömen",
    "keywords": [
      "recensioner",
      "betyg",
      "omdömen",
      "svara",
      "genomsnittligt betyg",
      "rykte"
    ],
    "summary": "Hur du ser och svarar på omdömen från dina kunder.",
    "content": [
      {
        "paragraphs": [
          "Under Recensioner ser du alla omdömen från dina kunder."
        ]
      },
      {
        "heading": "Du kan",
        "bullets": [
          "Se ditt genomsnittliga betyg",
          "Läsa alla omdömen med datum och kommentarer",
          "Svara på omdömen -- skriv ett svar som visas publikt under kundens omdöme"
        ]
      },
      {
        "paragraphs": [
          "Bra omdömen bygger ditt rykte och gör att fler kunder hittar dig. Ta dig tid att svara -- det visar att du bryr dig om kundnöjdheten."
        ]
      }
    ]
  },
  {
    "slug": "rostloggning",
    "title": "Röstloggning",
    "role": "provider",
    "section": "Dagligt arbete",
    "keywords": [
      "röstloggning",
      "arbetslogg",
      "diktera",
      "mikrofon",
      "AI",
      "logga arbete",
      "vokabulär"
    ],
    "summary": "Hur du snabbt dokumenterar utfört arbete genom att diktera eller skriva fritt med AI-stöd.",
    "content": [
      {
        "paragraphs": [
          "Under Logga arbete kan du snabbt dokumentera utfört arbete genom att diktera eller skriva fritt."
        ]
      },
      {
        "heading": "Så fungerar det",
        "steps": [
          "Gå till Logga arbete i leverantörsmenyn (eller tryck på den gröna mikrofon-knappen på mobil)",
          "Diktera med mikrofonen eller skriv i textfältet",
          "AI tolkar din text och föreslår vilken bokning arbetet tillhör",
          "Granska och justera -- AI:n visar en confidence-indikator",
          "Bekräfta för att spara arbetsloggen på bokningen"
        ]
      },
      {
        "heading": "Vokabulärinlärning",
        "bullets": [
          "Om du korrigerar AI:ns tolkning lär den sig dina termer",
          "Nästa gång du loggar arbete använder AI:n din personliga ordlista",
          "Max 50 termer sparas (äldsta fasas ut)"
        ]
      },
      {
        "tip": "Fungerar bäst med korta, koncisa beskrivningar (\"Verkade fram, normalställd, klipper lite kil\"). Du kan logga flera bokningar i rad med \"Logga nästa\"-flödet. Röstinspelning fungerar i Chrome och Safari. I Firefox används textfältet."
      },
      {
        "tip": "Den här funktionen kan vara inaktiverad och kanske inte är tillgänglig i alla konton."
      }
    ]
  },
  {
    "slug": "ruttplanering",
    "title": "Ruttplanering",
    "role": "provider",
    "section": "Ruttplanering",
    "keywords": [
      "ruttplanering",
      "rutt",
      "optimera",
      "körsträcka",
      "avstånd",
      "beställningar",
      "kartvy"
    ],
    "summary": "Hur du använder ruttplaneringen för att optimera din dag med flera besök.",
    "content": [
      {
        "paragraphs": [
          "Ruttplaneringen hjälper dig att optimera din dag när du har flera besök."
        ]
      },
      {
        "heading": "Bläddra bland beställningar",
        "paragraphs": [
          "Under Ruttplanering ser du flexibla beställningar från kunder i ditt område:"
        ],
        "bullets": [
          "Sorterade efter avstånd (närmast först)",
          "Filtrerbara på tjänstetyp, prioritet och datum",
          "Akuta beställningar markeras i rött",
          "Kartvy med markörer för varje beställning"
        ]
      },
      {
        "heading": "Skapa en optimerad rutt",
        "steps": [
          "Välj de beställningar du vill ta med",
          "Systemet beräknar automatiskt den mest effektiva ruttordningen",
          "Du ser total körsträcka och beräknad tid",
          "Justera ordningen manuellt om du vill",
          "Namnge rutten och välj datum",
          "Spara -- kunderna notifieras med beräknad ankomsttid"
        ]
      },
      {
        "paragraphs": [
          "Optimeringen använder avståndberäkning fågelvägen med en marginal på 20% för verklig vägsträcka, plus 10 minuters buffert mellan varje stopp."
        ]
      }
    ]
  },
  {
    "slug": "sla-ihop-konton",
    "title": "Slå ihop konton",
    "role": "provider",
    "section": "Kunder",
    "keywords": [
      "slå ihop",
      "merge",
      "sammanslagning",
      "dubbla konton",
      "manuell kund",
      "befintligt konto"
    ],
    "summary": "Hur du slår ihop en manuellt tillagd kund med ett befintligt riktigt konto.",
    "content": [
      {
        "paragraphs": [
          "Om en manuellt tillagd kund redan har skapat ett eget konto i Equinet (med en annan e-postadress eller separat registrering), kan du slå ihop de två kontona."
        ]
      },
      {
        "heading": "Så här gör du",
        "steps": [
          "Gå till Kunder i leverantörsmenyn",
          "Klicka på den manuellt tillagda kunden",
          "Klicka Slå ihop med befintligt konto",
          "Sök efter det riktiga kontot (via namn eller e-post)",
          "Bekräfta sammanslagningen"
        ]
      },
      {
        "heading": "Vad händer vid sammanslagning",
        "bullets": [
          "Alla bokningar överförs till det riktiga kontot",
          "Hästkopplingar bevaras",
          "Anteckningar och historik slås ihop",
          "Det manuella kontot tas bort",
          "Sammanslagningen är atomär -- allt eller inget sker"
        ]
      },
      {
        "paragraphs": [
          "Sammanslagningen kan inte ångras. Kontrollera att du valt rätt konto innan du bekräftar."
        ]
      }
    ]
  },
  {
    "slug": "stang-for-nya-kunder",
    "title": "Stäng för nya kunder",
    "role": "provider",
    "section": "Profil",
    "keywords": [
      "stäng",
      "nya kunder",
      "acceptera",
      "befintliga kunder",
      "toggle",
      "fullt schema"
    ],
    "summary": "Hur du stänger för nya kunder så att bara befintliga kunder kan boka hos dig.",
    "content": [
      {
        "paragraphs": [
          "Under Min profil hittar du en toggle \"Accepterar nya kunder\"."
        ],
        "bullets": [
          "Aktiverad (standard): Alla kunder kan boka hos dig",
          "Inaktiverad: Bara befintliga kunder kan boka"
        ]
      },
      {
        "paragraphs": [
          "Vem räknas som befintlig kund? En kund som har minst en genomförd bokning hos dig.",
          "Nya kunder som besöker din profil ser en informationsruta som förklarar att du inte tar emot nya kunder just nu. Befintliga kunder märker ingen skillnad."
        ],
        "tip": "Det här är användbart om du har fullt schema och bara vill fokusera på dina återkommande kunder."
      }
    ]
  },
  {
    "slug": "tillganglighet-och-schema",
    "title": "Tillgänglighet och schema",
    "role": "provider",
    "section": "Kalender",
    "keywords": [
      "tillgänglighet",
      "schema",
      "öppettider",
      "veckoschema",
      "undantag",
      "semester",
      "kalender",
      "stängt"
    ],
    "summary": "Hur du ställer in veckoschema, skapar undantag och använder kalendervyn.",
    "content": [
      {
        "heading": "Veckoschema",
        "paragraphs": [
          "Under Kalender ställer du in dina ordinarie öppettider per veckodag. Till exempel:"
        ],
        "bullets": [
          "Måndag-fredag: 08:00-17:00",
          "Lördag: 09:00-13:00",
          "Söndag: Stängt"
        ]
      },
      {
        "heading": "Undantag",
        "paragraphs": [
          "För enskilda datum kan du skapa undantag som överträder veckoschemat:"
        ],
        "bullets": [
          "Stängt en dag (semester, sjukdom, etc.)",
          "Ändrade tider (t.ex. 10:00-14:00 istället för ordinarie)",
          "Alternativ plats (om du jobbar från annan ort den dagen)"
        ]
      },
      {
        "paragraphs": [
          "Du kan ange en anledning (\"Semester\", \"Mässa i Jönköping\") och alternativa koordinater om du befinner dig på annan plats."
        ]
      },
      {
        "heading": "Kalendervy",
        "paragraphs": [
          "Kalendern visar en veckoöversikt med:"
        ],
        "bullets": [
          "Gröna block för lediga tider",
          "Röda block för bokade tider",
          "Svarta block för undantag"
        ]
      }
    ]
  },
  {
    "slug": "anvandarhantering",
    "title": "Användarhantering",
    "role": "admin",
    "section": "Hantering",
    "keywords": [
      "användare",
      "hantering",
      "blockera",
      "avblockera",
      "admin",
      "behörighet",
      "filter",
      "sök",
      "leverantör",
      "kund"
    ],
    "summary": "Hantera alla registrerade användare med sök, filter och åtgärder som blockering och adminbehörighet.",
    "content": [
      {
        "paragraphs": [
          "Under Användare ser du alla registrerade användare med sök och filter."
        ]
      },
      {
        "heading": "Filtrera på",
        "bullets": [
          "Typ (kund / leverantör)",
          "Fritextsökning i namn och e-post"
        ]
      },
      {
        "heading": "Åtgärder per användare",
        "bullets": [
          "Blockera/avblockera -- blockerade användare kan inte logga in",
          "Ge/ta bort admin-behörighet -- du kan inte ta bort din egen admin-behörighet"
        ]
      },
      {
        "paragraphs": [
          "Leverantörer visas med extra information: företagsnamn, antal bokningar, tjänster, genomsnittsbetyg och Fortnox-koppling."
        ]
      }
    ]
  },
  {
    "slug": "bokningshantering",
    "title": "Bokningshantering",
    "role": "admin",
    "section": "Hantering",
    "keywords": [
      "bokningar",
      "hantering",
      "avboka",
      "status",
      "datum",
      "filter",
      "admin"
    ],
    "summary": "Hantera alla bokningar med status- och datumfilter samt möjlighet att avboka med anledning.",
    "content": [
      {
        "paragraphs": [
          "Under Bokningar ser du alla bokningar med status- och datumfilter."
        ]
      },
      {
        "heading": "Åtgärder",
        "bullets": [
          "Avboka bokning -- ange en anledning som skickas till både kund och leverantör. Avbokningsmeddelandet prefixas med \"[Admin]\"."
        ]
      }
    ]
  },
  {
    "slug": "dashboard",
    "title": "Dashboard",
    "role": "admin",
    "section": "Översikt",
    "keywords": [
      "dashboard",
      "KPI",
      "statistik",
      "översikt",
      "trender",
      "intäkter",
      "bokningar",
      "användare",
      "leverantörer"
    ],
    "summary": "Admin-dashboarden visar KPI-kort, trendgrafer och snabblänkar för att ge en överblick över plattformens status.",
    "content": [
      {
        "paragraphs": [
          "Admin-panelen nås via /admin och kräver att din användare har admin-behörighet. Sidan är skyddad med både middleware och per-route kontroller."
        ]
      },
      {
        "heading": "KPI-kort",
        "paragraphs": [
          "Startsidan visar fyra klickbara KPI-kort:"
        ],
        "bullets": [
          "Användare -- totalt, kunder, leverantörer, nya denna månad",
          "Bokningar -- totalt, per status (väntande/bekräftade/genomförda/avbokade), genomförda denna månad",
          "Leverantörer -- totalt, aktiva, verifierade, väntande verifieringar",
          "Intäkter -- totalt genomfört belopp, belopp denna månad"
        ]
      },
      {
        "heading": "Trendgrafer",
        "bullets": [
          "Bokningar per vecka (senaste 8 veckorna) -- linjediagram med genomförda och avbokade",
          "Intäkter per månad (senaste 6 månaderna) -- stapeldiagram"
        ]
      },
      {
        "heading": "Onboarding-checklista",
        "paragraphs": [
          "Checklistan visar status för nya leverantörers onboarding:"
        ],
        "bullets": [
          "Fyll i företagsprofil",
          "Lägg till minst en tjänst",
          "Sätt öppettider",
          "Verifiera e-postadress"
        ]
      },
      {
        "heading": "Snabblänkar",
        "paragraphs": [
          "Snabblänkar till vanliga åtgärder som att skapa ny bokning, lägga till tjänst med mera."
        ]
      }
    ]
  },
  {
    "slug": "notifikationer",
    "title": "Notifikationer",
    "role": "admin",
    "section": "Kommunikation",
    "keywords": [
      "notifikationer",
      "meddelanden",
      "skicka",
      "målgrupp",
      "alla",
      "kunder",
      "leverantörer",
      "bulk"
    ],
    "summary": "Skicka notifikationer till alla användare eller en specifik målgrupp som kunder eller leverantörer.",
    "content": [
      {
        "paragraphs": [
          "Under Notifikationer kan du skicka meddelanden till användare."
        ]
      },
      {
        "heading": "Målgrupper",
        "bullets": [
          "Alla -- alla registrerade användare",
          "Kunder -- bara kunder",
          "Leverantörer -- bara leverantörer"
        ]
      },
      {
        "paragraphs": [
          "Ange rubrik och meddelande. Notifikationerna skapas i bulk och visas i användarnas klocka."
        ]
      }
    ]
  },
  {
    "slug": "recensionsmoderation",
    "title": "Recensionsmoderation",
    "role": "admin",
    "section": "Hantering",
    "keywords": [
      "recensioner",
      "moderation",
      "moderera",
      "ta bort",
      "kundrecension",
      "leverantörsrecension",
      "filter",
      "sök"
    ],
    "summary": "Moderera alla recensioner med filter och möjlighet att permanent ta bort olämpliga recensioner.",
    "content": [
      {
        "paragraphs": [
          "Under Recensioner ser du alla recensioner (både kund-till-leverantör och leverantör-till-kund)."
        ]
      },
      {
        "heading": "Filtrera på",
        "bullets": [
          "Typ (kundrecensioner / leverantörsrecensioner)",
          "Fritextsökning i kommentarer"
        ]
      },
      {
        "heading": "Åtgärder",
        "bullets": [
          "Ta bort recension -- permanent borttagning (kräver bekräftelse)"
        ]
      }
    ]
  },
  {
    "slug": "systeminstellningar",
    "title": "Systeminställningar",
    "role": "admin",
    "section": "System",
    "keywords": [
      "system",
      "inställningar",
      "feature flags",
      "flaggor",
      "hälsa",
      "cron",
      "databas",
      "e-post",
      "toggle"
    ],
    "summary": "Övervaka systemhälsa och hantera feature flags som styr vilka funktioner som är aktiva på plattformen.",
    "content": [
      {
        "paragraphs": [
          "Under System ser du:"
        ],
        "bullets": [
          "Systemhälsa -- databasstatus och svarstid",
          "Cron-status -- senaste påminnelsekörning"
        ]
      },
      {
        "heading": "Feature flags",
        "paragraphs": [
          "Feature flags styr vilka funktioner som är aktiva. Varje flagga kan slås av och på i realtid."
        ],
        "bullets": [
          "Röstloggning -- AI-baserad arbetsloggning",
          "Ruttplanering -- Ruttplaneringsverktyg",
          "Rutt-annonser -- Publicera ruttannonser",
          "Kundinsikter -- AI-genererade kundinsikter",
          "Besöksplanering -- Återbesöksplanering",
          "Gruppbokningar -- Gruppbokningsfunktionalitet (under utveckling)",
          "Affärsinsikter -- Utökad analytics-sida",
          "Självservice-ombokning -- Kunder kan boka om sina egna bokningar",
          "Återkommande bokningar -- Möjlighet att skapa återkommande bokningsserier",
          "Offlineläge -- PWA-stöd med offline-cachning av bokningar och rutter för leverantörer",
          "Följ leverantör -- Kunder kan följa leverantörer och få personliga ruttannonser",
          "Besöksplanering (kund) -- Kunder ser servicestatus-badges och kan sätta egna intervall"
        ]
      },
      {
        "paragraphs": [
          "Flaggor kan slås av och på i realtid. Ändringar sparas i Redis och gäller omedelbart."
        ]
      },
      {
        "heading": "Utveckling & Test",
        "bullets": [
          "E-post-toggle -- stäng av skarp e-postutskick (loggar istället). Användbart under utveckling och testning."
        ]
      }
    ]
  },
  {
    "slug": "tva-faktor-autentisering",
    "title": "Tvåfaktorautentisering (MFA)",
    "role": "admin",
    "section": "Säkerhet",
    "keywords": [
      "MFA",
      "tvåfaktor",
      "2FA",
      "TOTP",
      "autentisering",
      "säkerhet",
      "Google Authenticator",
      "Authy",
      "QR-kod",
      "verifieringskod"
    ],
    "summary": "Hur du aktiverar och använder tvåfaktorautentisering (MFA) för att skydda ditt admin-konto.",
    "content": [
      {
        "paragraphs": [
          "Som admin kan du aktivera tvåfaktorautentisering (MFA) för att lägga till ett extra skyddslager på ditt konto. MFA kräver att du anger en tidsbegränsad kod från en autentiseringsapp vid varje inloggning."
        ]
      },
      {
        "heading": "Aktivera MFA",
        "steps": [
          "Logga in på ditt admin-konto",
          "Gå till Kontoinställningar",
          "Klicka på **Aktivera tvåfaktorautentisering**",
          "Skanna QR-koden med din autentiseringsapp (t.ex. Google Authenticator, Authy eller Microsoft Authenticator)",
          "Ange den 6-siffriga koden som visas i appen",
          "Klicka **Verifiera** -- MFA är nu aktiverat"
        ]
      },
      {
        "heading": "Logga in med MFA",
        "steps": [
          "Ange ditt e-postadress och lösenord som vanligt",
          "Du omdirigeras till en verifieringssida",
          "Öppna din autentiseringsapp och ange den aktuella 6-siffriga koden",
          "Klicka **Verifiera** -- du är nu inloggad"
        ],
        "paragraphs": [
          "Koder är giltiga i 30 sekunder. Om koden har gått ut -- vänta på nästa kod i appen."
        ]
      },
      {
        "heading": "Autentiseringsappar som fungerar",
        "bullets": [
          "**Google Authenticator** (iOS / Android)",
          "**Authy** (iOS / Android / Desktop)",
          "**Microsoft Authenticator** (iOS / Android)",
          "Alla appar som stöder TOTP (RFC 6238)"
        ]
      },
      {
        "heading": "Viktigt att veta",
        "bullets": [
          "MFA gäller enbart admin-konton",
          "Förlora aldrig åtkomst till din autentiseringsapp -- det finns för tillfället ingen självservice-återställning",
          "Kontakta Equinet om du är utlåst"
        ],
        "tip": "Aktivera MFA omedelbart efter att du fått admin-behörighet. Det är ditt viktigaste skydd mot obehörig åtkomst."
      }
    ]
  },
  {
    "slug": "verifieringsgranskning",
    "title": "Verifieringsgranskning",
    "role": "admin",
    "section": "Hantering",
    "keywords": [
      "verifiering",
      "granskning",
      "kompetens",
      "certifikat",
      "diplom",
      "godkänn",
      "avvisa",
      "leverantör"
    ],
    "summary": "Granska leverantörers kompetensansökningar och godkänn eller avvisa med kommentar.",
    "content": [
      {
        "paragraphs": [
          "Under Verifieringar granskar du leverantörers kompetensansökningar."
        ]
      },
      {
        "heading": "För varje ansökan ser du",
        "bullets": [
          "Leverantörsnamn och företag",
          "Kompetenstyp, titel, utfärdare och år",
          "Uppladdade bilder (diplom, certifikat, etc.)"
        ]
      },
      {
        "heading": "Åtgärder",
        "bullets": [
          "Godkänn -- kompetensen visas med grön badge på leverantörens profil",
          "Avvisa -- skriv en kommentar som förklarar varför (leverantören kan redigera och skicka in igen)"
        ]
      }
    ]
  }
] as const satisfies HelpArticle[]
